version: "3.8"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - my-pg-data-1:/var/lib/postgresql/data/
    env_file:
      - environment
    restart: always

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery worker --app=core --loglevel=info
    working_dir: ./core
    volumes:
      - ./core:/opt/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - CELLOSIGN_DEBUG=no
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - environment
    restart: always
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_USER=admin

  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/opt/app
    ports:
      - "8000:8000"
    env_file:
      - environment
    depends_on:
      - postgres
      - redis


volumes:
  my-pg-data-1:
    driver: local
